services:
  - type: web
    name: my-django-api
    env: python
    buildCommand: ""
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.settings